package:
  name: nest-simulator
  version: 2.8.0

source:
  git_tag: v2.8.0
  git_url: https://github.com/nest/nest-simulator.git

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython
    - readline
    - autoconf
    - automake
    - m4
    #- perl
    - libtool

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - ipython

# automatic replacement did not work, force it
build:
  binary_has_prefix_files:
    - bin/nest
    - bin/sli
    - lib/python2.7/site-packages/nest/pynestkernel.so
  has_prefix_files:
    - bin/nest_vars.sh
    - bin/nest-config
    #- bin/nest_vars.sh
    - lib/python2.7/site-packages/nest/pynestkernel.la
    - share/nest/extras/do_tests.sh
    - share/nest/extras/emacs/sli.el

test:
  imports:
    - nest

about:
  home: http://www.nest-simulator.org/
  license: GPL
  summary: "NEST is a simulator for spiking neural network models."
